# Generated by Django 4.2 on 2023-05-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_in_post_comment_in_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_by',
            field=models.CharField(default='test', max_length=50),
        ),
    ]
